[package]
name = "macchina"
version = "0.1.4"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
description = "System information fetcher, written in Rust."
keywords = ["system", "fetch", "command-line"]

repository = "https://github.com/grtcdr/macchina"
documentation = "https://github.com/grtcdr/macchina"

license = "MIT"
readme = "README.md"

[dependencies]
colored = "2"
num_cpus = "1.13.0"
nix = "0.19.0"
bytesize = "1.0.1"
clap = "2.33.3"
rand = "0.8.3"
