[package]
name = "macchina"
version = "0.1.0"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
num_cpus = "1.13.0"
nix = "0.19.0"