[package]
name = "macchina"
version = "0.5.3"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
description = "System information fetcher"
keywords = ["system", "fetch", "cli"]
repository = "https://github.com/grtcdr/macchina"
license = "MIT"
readme = "README_CARGO.md"

[profile.release]
opt-level = 3
debug = false

[dependencies]
colored = "2.0.0"
num_cpus = "1.13.0"
bytesize = "1.0.1"
clap = "2.33.3"
rand = "0.8.3"
lazy_static = "1.4.0"
macchina-read = { path = "macchina-read/" }