[package]
name = "macchina"
version = "0.1.0"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
description = "System information fetcher, written in Rust."
keywords = ["system", "fetch", "command-line"]

repository = "https://github.com/grtcdr/macchina"
documentation = "https://github.com/grtcdr/macchina"

license = "MIT"
license-file = "LICENSE"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
num_cpus = "1.13.0"
nix = "0.19.0"
bytesize = "1.0.1"
clap = "2.33.3"