[package]
name = "macchina-read"
version = "0.1.0"
authors = ["grtcdr <ba.tahaaziz@gmail.com>", "Marvin Haschker <marvin@haschker.me>"]
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.88"
nix = "0.20.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.1"
mach = "0.3.2"
sysctl = "0.4.0"
objc = "0.2.7"
objc-foundation = "0.1.1"